### ISSUE TITLE
Hi, jshtok

### ISSUE THREAD

**Issue by cxcjcj** [jshtok/RepMet#12]
Hi, jshtok
I tried to train your model,and here is a little problem that i found：

Traceback (most recent call last):
  File "./experiments/fpn_end2end_train_test.py", line 31, in <module>
    train_end2end.main()
  File "./experiments/../fpn/train_end2end.py", line 292, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "./experiments/../fpn/train_end2end.py", line 120, in train_net
    num_ex_per_class = num_ex_per_class)
  File "./experiments/../fpn/../lib/utils/load_data.py", line 10, in load_gt_roidb
    per_category_epoch_max=per_category_epoch_max,classes_list_fname=classes_list_fname,num_ex_per_class=num_ex_per_class)
  File "./experiments/../fpn/../lib/dataset/imagenet.py", line 58, in __init__
    synsets = sio.loadmat(os.path.join(self.devkit_path, 'data', 'meta_'+base_modifier+'.mat'))
  File "/home/cx/.conda/envs/RepMet/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 207, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/cx/.conda/envs/RepMet/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 62, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
  File "/home/cx/.conda/envs/RepMet/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 37, in _open_file
    return open(file_like, 'rb'), True
IOError: [Errno 2] No such file or directory: './data/imagenet/ILSVRC/devkit/data/meta_clsloc.mat'

I am looking forward to your replay.

**Comment by duynn912** [comment]
Hi @cxcjcj,
To me, I think this file is a matlab file of imagenet  so I down it from https://github.com/leonardblier/ImageNetEval/blob/master/meta_clsloc.mat. It works for me

**Comment by cxcjcj** [comment]
Thank you very much for your reply. I will try as you suggested.

**Comment by frakersa** [comment]
> Thank you very much for your reply. I will try as you suggested.

Hi, i'm confronted with the same problem as you,have you solved this erro? I've tried to download the file by @duynn912 ,but it reminded me that file is not a binary mat file, so I couldn't load it.
